/****************************************************************************
*   Generated by ACUITY 6.21.1
*   Match ovxlib 1.1.30
*
*   Neural Network appliction post-process header file for YuNet Network Binary (.nb format)
****************************************************************************/
#ifndef _VNN_POST_PROCESS_YUNET_NETWORK_BINARY_H_
#define _VNN_POST_PROCESS_YUNET_NETWORK_BINARY_H_

#include <opencv2/opencv.hpp>
#include <vector>

// Structure to hold detected face with landmarks
struct YunetFaceObject {
    cv::Rect rect;              // Bounding box (x, y, w, h)
    float landmarks[10];        // 5 landmarks x 2 coordinates (x, y)
    float confidence;           // Detection confidence score
};

vsi_status vnn_PostProcessYunet
    (
    vsi_nn_graph_t *graph,
    std::vector<YunetFaceObject>& faces,
    int inputW,
    int inputH
    );

const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMapYunet();

uint32_t vnn_GetPostProcessMapCountYunet();

#endif
