/****************************************************************************
*   Generated by ACUITY 6.21.1
*   Match ovxlib 1.1.30
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_H_
#define _VNN_POST_PROCESS_H_

vsi_status vnn_PostProcess
    (
    vsi_nn_graph_t *graph,
    const char **inputs,
    uint32_t input_num
    );

vsi_status vnn_PostProcess_
    (
    vsi_nn_graph_t *graph,
    const char **inputs,
    uint32_t input_num
    );

const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMap();

uint32_t vnn_GetPostProcessMapCount();

#endif
