/****************************************************************************
*   Generated by ACUITY 6.21.1
*   Match ovxlib 1.1.30
*
*   Neural Network appliction pre-process header file for YuNet Network Binary (.nb format)
****************************************************************************/
#ifndef _VNN_PRE_PROCESS_YUNET_NETWORK_BINARY_H_
#define _VNN_PRE_PROCESS_YUNET_NETWORK_BINARY_H_

#include "vnn_pre_process.h"

vsi_status vnn_PreProcessYunet
    (
    vsi_nn_graph_t *graph,
    uint32_t input_num,
    uint8_t *input_buf
    );

vsi_bool vnn_UseImagePreprocessNodeYunet();

void vnn_ReleaseBufferImageYunet();

vsi_size_t vnn_LoadFP32DataFromTextFileYunet
    (
    const char * fname,
    uint8_t ** buffer_ptr,
    vsi_size_t * buffer_sz
    );

vsi_size_t vnn_LoadRawDataFromBinaryFileYunet
    (
    const char * fname,
    uint8_t ** buffer_ptr,
    vsi_size_t * buffer_sz
    );

const vsi_nn_preprocess_map_element_t * vnn_GetPreProcessMapYunet();

uint32_t vnn_GetPreProcessMapCountYunet();

#endif
